spring:
  cloud:
    gateway:
      routes:
        - id: YelpService
          uri: https://api.yelp.com
          predicates:
             - Path=/v3/**
             #- Path=/api/**
          #filters:
            #- RewritePath=/api/(?<segment>/?.*), /api/validation
            #- IDLValidationFilter

