spring:
  cloud:
    gateway:
      routes:
        - id: YelpAPI
          uri: https://api.yelp.com
          predicates:
            - Path=/v3/businesses/**
          filters:
            - IDLDetectionFilter
            #- IDLDetectionAndExplanationFilter