name: Deploy to Heroku
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: heroku/deploy-via-git-action@v1
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: idlgateway
